flags: {}
packages:
- lambdabot/
- lambdabot-core/
- lambdabot-haskell-plugins/
- lambdabot-irc-plugins/
- lambdabot-misc-plugins/
- lambdabot-novelty-plugins/
- lambdabot-reference-plugins/
- lambdabot-social-plugins/
- lambdabot-trusted/
extra-deps:
- IOSpec-0.3
- QuickCheck-safe-0.1.0.2
- Stream-0.4.7.2
- aeson-1.1.0.0
- arrows-0.4.4.1
- base-compat-0.9.2
- brainfuck-0.1.0.3
- haskell-src-exts-1.19.1
- haskell-src-exts-simple-1.19.0.0
- hoogle-5.0.9
- lazysmallcheck-0.6
- mueval-0.9.3
- prim-uniq-0.1.0.1
- process-extras-0.7.1
- show-0.6
- unlambda-0.1.4.2
resolver: lts-7.20
